export enum Gateway {
  GET = "/gateway",
  GET_BOT = "/gateway/bot",
}

export enum Opcode {
  DISPATCH,
  HEARTBEAT,
  IDENTIFY,
  PRESENCE_UPDATE,
  VOICE_STATE_UPDATE,
  RESUME = 6,
  RECONNECT,
  REQUEST_GUILD_MEMBERS,
  INVALID,
  HELLO,
  HEARTBEAT_ACK,
}

export enum OpcodeClose {
  UNKNOWN = 4000,
  UNKNOWN_OPCODE,
  DECODE_ERROR,
  AUTH_NONE,
  AUTH_FAIL,
  AUTH_REPEAT,
  INVALID_SEQ = 4007,
  RATE_LIMIT,
  SESSION_TIMED,
  SHARD_INVALID,
  SHARD_REQ,
  INTENT_INVALID,
  INTENT_NOTALLOWED,
}

export enum Intents {
  GUILDS = 1 << 0,
  GUILD_MEMBERS = 1 << 1,
  GUILD_BANS = 1 << 2,
  GUILD_EMOJIS = 1 << 3,
  GUILD_INTEGRATIONS = 1 << 4,
  GUILD_WEBHOOKS = 1 << 5,
  GUILD_INVITES = 1 << 6,
  GUILD_VOICE_STATS = 1 << 7,
  GUILD_PRESENCES = 1 << 8,
  GUILD_MESSAGES = 1 << 9,
  GUILD_MESSAGE_REACTIONS = 1 << 10,
  GUILD_MESSAGE_TYPING = 1 << 11,
  DIRECT_MESSAGES = 1 << 12,
  DIRECT_MESSAGE_REACTIONS = 1 << 13,
  DIRECT_MESSAGE_TYPING = 1 << 14,
}
